---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sgw
  name: sgw-service
  namespace: platform
spec:
  ports:
  - port: 443
    name: https
  - port: 80
    name: http
  selector:
    app: sgw
  type: LoadBalancer
